//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.Modules = new HashSet<Module>();
            this.ModulesInRoles = new HashSet<ModulesInRole>();
        }
    
        public System.Guid Id { get; set; }
        public string ActionName { get; set; }
    
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<ModulesInRole> ModulesInRoles { get; set; }
    }
}
