//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew
    {
        public Crew()
        {
            this.Crew_Whitelist = new HashSet<Crew_Whitelist>();
        }
    
        public string Barcode { get; set; }
        public string Nama { get; set; }
        public System.DateTime Tanggal_Daftar { get; set; }
        public string Status { get; set; }
        public string Airport { get; set; }
        public string Company_Airways { get; set; }
    
        public virtual ICollection<Crew_Whitelist> Crew_Whitelist { get; set; }
    }
}
