//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew_Whitelist
    {
        public int Id { get; set; }
        public string Barcode { get; set; }
        public System.DateTime Tanggal_Awal { get; set; }
        public System.DateTime Tanggal_Akhir { get; set; }
    
        public virtual Crew Crew { get; set; }
    }
}
