//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public currency()
        {
            //this.assets = new HashSet<asset>();
            //this.deposits = new HashSet<deposit>();
            //this.giroes = new HashSet<giro>();
            //this.mutual_funds = new HashSet<mutual_funds>();
            //this.non_unit_linked_insurance = new HashSet<non_unit_linked_insurance>();
            //this.obligations = new HashSet<obligation>();
            //this.savings = new HashSet<saving>();
        }
    
        public int id { get; set; }
        public string currency1 { get; set; }
        public double value { get; set; }
        public bool is_delete { get; set; }
    
        //public virtual ICollection<asset> assets { get; set; }
        //public virtual ICollection<deposit> deposits { get; set; }
        //public virtual ICollection<giro> giroes { get; set; }
        //public virtual ICollection<mutual_funds> mutual_funds { get; set; }
        //public virtual ICollection<non_unit_linked_insurance> non_unit_linked_insurance { get; set; }
        //public virtual ICollection<obligation> obligations { get; set; }
        //public virtual ICollection<saving> savings { get; set; }
    }
}
