//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fid_item
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public string title { get; set; }
        public System.DateTime plan_finish_date { get; set; }
        public Nullable<System.DateTime> actual_finish_date { get; set; }
        public int menu_order { get; set; }
        public bool deleted { get; set; }
    
        public virtual project project { get; set; }
    }
}
