//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident_report
    {
        public int id { get; set; }
        public string incident_location { get; set; }
        public System.DateTime date_incident { get; set; }
        public string title { get; set; }
        public string incident_type { get; set; }
        public string actual_loss_severity { get; set; }
        public string potential_loss_severity { get; set; }
        public string probability { get; set; }
        public string factual_information { get; set; }
        public string cost_estimate { get; set; }
        public string immediate_action { get; set; }
        public string prepared_by { get; set; }
        public string ack_supervisor { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<System.DateTime> ack_date { get; set; }
        public string prepared_position { get; set; }
        public string ack_position { get; set; }
        public string approved_initiator_superintendent { get; set; }
        public Nullable<System.DateTime> approved_initiator_superintendent_date { get; set; }
        public string approved_she_superintendent { get; set; }
        public Nullable<System.DateTime> approved_she_superintendent_date { get; set; }
        public string approved_safety_supervisor { get; set; }
        public Nullable<System.DateTime> approved_safety_supervisor_date { get; set; }
        public string approved_field_manager { get; set; }
        public Nullable<System.DateTime> approved_field_manager_date { get; set; }
        public bool is_investigation_required { get; set; }
        public string investigation_request_by { get; set; }
        public string investigation_lead_by { get; set; }
        public bool is_cutoff_date { get; set; }
        public int project_id { get; set; }
        public bool is_final { get; set; }
    
        public virtual project project { get; set; }
    }
}
