//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_investment_prognosis
    {
        public int id { get; set; }
        public int m_investment_prognosis_period_id { get; set; }
        public int year { get; set; }
        public int month { get; set; }
        public double value { get; set; }
    
        public virtual m_investment_prognosis_period m_investment_prognosis_period { get; set; }
    }
}
