//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_investment_prognosis_period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_investment_prognosis_period()
        {
            this.m_investment_prognosis = new HashSet<m_investment_prognosis>();
        }
    
        public int id { get; set; }
        public int m_project_id { get; set; }
        public int month { get; set; }
        public int year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_investment_prognosis> m_investment_prognosis { get; set; }
        public virtual m_project m_project { get; set; }
    }
}
