//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_project_under_study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_project_under_study()
        {
            this.m_project_under_study_task = new HashSet<m_project_under_study_task>();
        }
    
        public int id { get; set; }
        public int num { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string summary { get; set; }
        public string action_plan { get; set; }
        public Nullable<int> project_id { get; set; }
        public int project_under_study_id { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_time { get; set; }
        public bool is_deleted { get; set; }
        public string approval_message { get; set; }
    
        public virtual project project { get; set; }
        public virtual project_under_study project_under_study { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_project_under_study_task> m_project_under_study_task { get; set; }
    }
}
