//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_project_gallery
    {
        public int id { get; set; }
        public int m_project_id { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public int order_num { get; set; }
        public bool is_show { get; set; }
    
        public virtual m_project m_project { get; set; }
    }
}
