//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_project_under_study_task
    {
        public int id { get; set; }
        public int m_project_under_study_id { get; set; }
        public string name { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime plan_finish_date { get; set; }
        public Nullable<System.DateTime> actual_finish_date { get; set; }
        public byte menu_order { get; set; }
    
        public virtual m_project_under_study m_project_under_study { get; set; }
    }
}
