//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_project()
        {
            this.m_investment = new HashSet<m_investment>();
            this.m_investment_actual = new HashSet<m_investment_actual>();
            this.m_investment_prognosis_period = new HashSet<m_investment_prognosis_period>();
            this.m_project_gallery = new HashSet<m_project_gallery>();
            this.m_rca = new HashSet<m_rca>();
            this.m_task = new HashSet<m_task>();
            this.contractors = new HashSet<contractor>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> contractor_id { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime finish_date { get; set; }
        public Nullable<bool> highlight { get; set; }
        public string project_stage { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<double> budget { get; set; }
        public string currency { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> pmc_id { get; set; }
        public string summary { get; set; }
        public Nullable<int> company_id { get; set; }
        public string status_non_technical { get; set; }
        public bool is_completed { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public int project_id { get; set; }
        public System.DateTime submit_for_approval_time { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_time { get; set; }
        public bool deleted { get; set; }
        public string approval_message { get; set; }
        public string status_technical { get; set; }
        public string scurve_data { get; set; }
    
        public virtual company company { get; set; }
        public virtual contractor contractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_investment> m_investment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_investment_actual> m_investment_actual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_investment_prognosis_period> m_investment_prognosis_period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_project_gallery> m_project_gallery { get; set; }
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_rca> m_rca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_task> m_task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contractor> contractors { get; set; }
    }
}
