//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_rca
    {
        public int id { get; set; }
        public string @event { get; set; }
        public string whys { get; set; }
        public string action_plan { get; set; }
        public string pic { get; set; }
        public System.DateTime due_date { get; set; }
        public int m_project_id { get; set; }
        public double progress { get; set; }
    
        public virtual m_project m_project { get; set; }
    }
}
