//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_task_progress
    {
        public int id { get; set; }
        public int m_task_id { get; set; }
        public Nullable<double> week_progress { get; set; }
        public string description { get; set; }
        public System.DateTime finish_date { get; set; }
    
        public virtual m_task m_task { get; set; }
    }
}
