//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_task()
        {
            this.m_task1 = new HashSet<m_task>();
            this.m_task_progress = new HashSet<m_task_progress>();
            this.m_task_recovery = new HashSet<m_task_recovery>();
            this.m_task_schedule = new HashSet<m_task_schedule>();
        }
    
        public int id { get; set; }
        public int m_project_id { get; set; }
        public string title { get; set; }
        public Nullable<double> weight { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime finish_date { get; set; }
        public int menu_order { get; set; }
        public Nullable<int> parent_id { get; set; }
    
        public virtual m_project m_project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_task> m_task1 { get; set; }
        public virtual m_task m_task2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_task_progress> m_task_progress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_task_recovery> m_task_recovery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_task_schedule> m_task_schedule { get; set; }
    }
}
