//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulesInRole
    {
        public ModulesInRole()
        {
            this.Actions = new HashSet<Action>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid ModuleId { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Action> Actions { get; set; }
    }
}
