//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ditgas_pmoEntities : DbContext
    {
        public ditgas_pmoEntities()
            : base("name=ditgas_pmoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action_plan_progress> action_plan_progress { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<company_user> company_user { get; set; }
        public virtual DbSet<contractor> contractors { get; set; }
        public virtual DbSet<fid_item> fid_item { get; set; }
        public virtual DbSet<incident_report> incident_report { get; set; }
        public virtual DbSet<leading_indicator> leading_indicator { get; set; }
        public virtual DbSet<m_investment> m_investment { get; set; }
        public virtual DbSet<m_investment_actual> m_investment_actual { get; set; }
        public virtual DbSet<m_investment_prognosis> m_investment_prognosis { get; set; }
        public virtual DbSet<m_investment_prognosis_period> m_investment_prognosis_period { get; set; }
        public virtual DbSet<m_project> m_project { get; set; }
        public virtual DbSet<m_project_gallery> m_project_gallery { get; set; }
        public virtual DbSet<m_project_under_study> m_project_under_study { get; set; }
        public virtual DbSet<m_project_under_study_task> m_project_under_study_task { get; set; }
        public virtual DbSet<m_rca> m_rca { get; set; }
        public virtual DbSet<m_task> m_task { get; set; }
        public virtual DbSet<m_task_progress> m_task_progress { get; set; }
        public virtual DbSet<m_task_recovery> m_task_recovery { get; set; }
        public virtual DbSet<m_task_recovery_schedule> m_task_recovery_schedule { get; set; }
        public virtual DbSet<m_task_schedule> m_task_schedule { get; set; }
        public virtual DbSet<outcome> outcomes { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<project_display> project_display { get; set; }
        public virtual DbSet<project_gallery> project_gallery { get; set; }
        public virtual DbSet<project_under_study> project_under_study { get; set; }
        public virtual DbSet<project_under_study_task> project_under_study_task { get; set; }
        public virtual DbSet<rca_template> rca_template { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<task_activity> task_activity { get; set; }
        public virtual DbSet<task_progress> task_progress { get; set; }
        public virtual DbSet<task_recovery> task_recovery { get; set; }
        public virtual DbSet<task_recovery_schedule> task_recovery_schedule { get; set; }
        public virtual DbSet<task_schedule> task_schedule { get; set; }
        public virtual DbSet<weather> weathers { get; set; }
        public virtual DbSet<weekly_hse> weekly_hse { get; set; }
        public virtual DbSet<weekly_rca> weekly_rca { get; set; }
        public virtual DbSet<weekly_report> weekly_report { get; set; }
        public virtual DbSet<project_notes> project_notes { get; set; }
    }
}
