//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.task1 = new HashSet<task>();
            this.task_recovery = new HashSet<task_recovery>();
            this.task_schedule = new HashSet<task_schedule>();
            this.task_activity = new HashSet<task_activity>();
            this.task_progress = new HashSet<task_progress>();
        }
    
        public int id { get; set; }
        public int project_id { get; set; }
        public string title { get; set; }
        public Nullable<double> weight { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime finish_date { get; set; }
        public int menu_order { get; set; }
        public bool deleted { get; set; }
        public Nullable<int> parent_id { get; set; }
    
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> task1 { get; set; }
        public virtual task task2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_recovery> task_recovery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_schedule> task_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_activity> task_activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_progress> task_progress { get; set; }
    }
}
