//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKaryawan
    {
        public int id { get; set; }
        public string nama_karyawan { get; set; }
        public Nullable<int> umur { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string pendidikan { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> tanggal_masuk { get; set; }
    }
}
