//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserManagement : DbContext
    {
        public UserManagement()
            : base("name=UserManagement")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //MANY-TO-MANY
            modelBuilder.Entity<Module>().
                HasMany(c => c.Actions).
                WithMany(p => p.Modules).
                Map(
                    m =>
                    {
                        m.MapLeftKey("ModuleId");
                        m.MapRightKey("ActionId");
                        m.ToTable("ActionsInModules");
                    });

            modelBuilder.Entity<ModulesInRole>().
                HasMany(c => c.Actions).
                WithMany(p => p.ModulesInRoles).
                Map(
                    m =>
                    {
                        m.MapLeftKey("ModuleInRoleId");
                        m.MapRightKey("ActionId");
                        m.ToTable("ActionsInModulesChosen");
                    });

            //ONE-TO-ONE
            modelBuilder.Entity<Membership>().HasRequired(a => a.User).WithRequiredPrincipal(b => b.Membership);
            modelBuilder.Entity<Profile>().HasRequired(a => a.User).WithRequiredPrincipal(b => b.Profile);

        }
    
        public DbSet<Action> Actions { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<ModulesInRole> ModulesInRoles { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }

        public DbSet<company> company { get; set; }
        public DbSet<currency> currency { get; set; }
        public DbSet<log> log { get; set; }
    }
}
