//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class weekly_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public weekly_report()
        {
            this.action_plan_progress = new HashSet<action_plan_progress>();
            this.task_activity = new HashSet<task_activity>();
            this.task_progress = new HashSet<task_progress>();
            this.weathers = new HashSet<weather>();
            this.weekly_hse = new HashSet<weekly_hse>();
            this.weekly_rca = new HashSet<weekly_rca>();
        }
    
        public int id { get; set; }
        public int project_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime finish_date { get; set; }
        public string photo { get; set; }
        public string prepared_company { get; set; }
        public string prepared_name { get; set; }
        public string prepared_position { get; set; }
        public byte status { get; set; }
        public bool deleted { get; set; }
        public string approved_company { get; set; }
        public string approved_name { get; set; }
        public string approved_position { get; set; }
        public string acknowledged_company { get; set; }
        public string acknowledged_name { get; set; }
        public string acknowledged_position { get; set; }
        public Nullable<int> loss_time { get; set; }
        public string attachment_documents { get; set; }
        public string attachment_photos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<action_plan_progress> action_plan_progress { get; set; }
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_activity> task_activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_progress> task_progress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weather> weathers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weekly_hse> weekly_hse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weekly_rca> weekly_rca { get; set; }
    }
}
