//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class weekly_rca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public weekly_rca()
        {
            this.action_plan_progress = new HashSet<action_plan_progress>();
        }
    
        public int id { get; set; }
        public int weekly_report_id { get; set; }
        public string @event { get; set; }
        public string whys { get; set; }
        public string action_plan { get; set; }
        public string pic { get; set; }
        public System.DateTime due_date { get; set; }
        public bool deleted { get; set; }
        public int project_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<action_plan_progress> action_plan_progress { get; set; }
        public virtual project project { get; set; }
        public virtual weekly_report weekly_report { get; set; }
    }
}
