//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class weekly_hse
    {
        public int weekly_report_id { get; set; }
        public Nullable<System.DateTime> cutoff_date { get; set; }
        public Nullable<int> direct_manpower { get; set; }
        public Nullable<int> direct_manhour { get; set; }
        public Nullable<int> direct_lost_time_injuries { get; set; }
        public Nullable<int> indirect_manpower { get; set; }
        public Nullable<int> indirect_manhour { get; set; }
        public Nullable<int> indirect_lost_time_injuries { get; set; }
        public Nullable<int> direct_lost_time_accident { get; set; }
        public Nullable<int> indirect_lost_time_accident { get; set; }
        public int id { get; set; }
        public Nullable<int> direct_safe_mh { get; set; }
        public Nullable<int> indirect_safe_mh { get; set; }
    
        public virtual weekly_report weekly_report { get; set; }
    }
}
